name: bank_mas_rewrite
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.2
  logger: ^1.3.0
  cached_network_image: ^3.2.3
  skeletons: ^0.0.3
  url_launcher: ^6.1.10
  flutter_localization: ^0.1.10
  flutter_localizations:
    sdk: flutter
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  mockito: ^5.3.2

flutter: 
  uses-material-design: true

